import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Providers from "@/shared/providers";
import { Header, NavItem } from "@/widgets/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Header title="PLANIT" avatar="P">
            <NavItem href="/dashboard">Dashboard</NavItem>
            <NavItem href="/attendance">Attendance</NavItem>
          </Header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
